### ISSUE TITLE
if there is an empty value for a cell, program rendering template's value instead of being blank

### ISSUE THREAD

**Issue by jameelgrand** [Polyconseil/xlsx_streaming#10] opened 2020-11-19 09:28 UTC
my template is:
name, grade
"arun","b"

my data is:
[["karan",""],["vijay","b"]

output:
name, grade
"karan","b"
"vijay","b"

expected output:
name, grade
"karan",""
"vijay","b"

**Comment by dbaty** [comment] 2020-11-30 10:29
Hello. I cannot reproduce this issue. I created an XLSX template file (downloadable [here](https://a.tmp.ninja/L0nQNbnY6Qir.xlsx) for 48 hours) with LibreOffice.

Then:

```python
import pathlib
import xlsx_streaming

data = [["karan", ""], ["vijay", "b"]]
template = pathlib.Path('/path/to/template.xlsx')
stream = xlsx_streaming.stream_queryset_as_xlsx(data, template)
out = b''.join(chunk for chunk in stream)
pathlib.Path('/path/to/the/result.xlsx').write_bytes(out)
```

The resulting file is as you expect (and not as you got), i.e. with an empty grade on the first line:

![resulting-spreadhseet](https://user-images.githubusercontent.com/471321/100598609-42945a00-32ff-11eb-8617-6cf5be8ab4be.png)


Can you double-check that you can reproduce your bug? If so, can you provide your template file?

**Comment by dbaty** [comment] 2021-01-22 08:59
I'll suppose that this is not a pressing issue, or not an issue at all. Closing it! :)

**Closed by dbaty** 2021-01-22 08:59 UTC
